### ISSUE TITLE
Missing `intTestDbCfg.json` file breaks NH test

### ISSUE THREAD

**Issue by arobson** [LeanKit-Labs/node-hilo#1]
Error: Cannot find module './intTestDbCfg.json'
      at Context.<anonymous> (spec/integration/nhibernate.comparisons.spec.js:46:10)

Looks like the file didn't make it into the repository.

**Comment by ifandelse** [comment]
That was intentional. The Readme explains you need to create one as I didn't want to store creds in the repo. also I need to finish the seriate changes before this is reviewed.

**Comment by arobson** [comment]
Oops. I just pulled the code and ran tests before I even tried to read through the doc.

**Comment by ifandelse** [comment]
I have local changes staged that makes node-Hilo use seriate's transaction context explicitly. Hope to get those up today
