### ISSUE TITLE
Should follow our existing conventions for Node projects

### ISSUE THREAD

**Issue by arobson** [LeanKit-Labs/node-hilo#2]
Our Node projects use several conventions: `biggulp`, a standard Gulpfile and a specific directory structure and set of standard files for consistency. Create a PR for this project that will bring it in-line with our conventions.

**Comment by ifandelse** [comment]
@arobson we will look into it. We had been planning to evaluate biggulp (on the web side of things) and try to align anything so that it could potentially serve both teams, just hadn't gotten to it yet. As far as the other things - where can I find info on standard files and directory structure?
